### PR TITLE
Added task fuction

### PR DESCRIPTION
**Pull request by Linxianyunqing**
I have added the task model in this project. But there are some thing wrong. When you want to created a new task, if you press the "add newtask" button, the project will breakdown. The reaon for this error may be there are **2** floatingbuttons in the task page. I don't find your code of floatingbutton. My code of floatingbutton is in the 108 line in task_pages.dart.

### CODE REVIEW

**Comment by derec30240** [comment]
You shouldn't create a new `floatingActionButton` in `task_page`. Instead, you should add the function to that one in the `home_page`. Because I'm not available for a few days, you can try it on yourself.

**Review by derec30240 — CHANGES_REQUESTED** [review]
You shouldn't create a new `floatingActionButton` in `task_page`. Instead, you should add the function to that one in the `home_page`. Because I'm not available for a few days, you can try it on yourself.

**Comment by derec30240** [comment]
> You shouldn't create a new `floatingActionButton` in `task_page`. Instead, you should add the function to that one in the `home_page`. Because I'm not available for a few days, you can try it on yourself.

For example, yoy can modify the `floatingActionPage.onPressed()` in `home_page` in this way:

```dart
floatingActionButton: FloatingActionButton(
  onPressed: () {
    (globalController.selectedHomeIndex.value == 0)
      ? Get.to(() => NoteEditPage(type: 'add', title: '', content: ''))
      : Get.to(() => TaskEditPage());
  },
```

Then delete the `floatingActionButton` in the `task_page`, because it's just the body of the`HomePage` when `globalController.selectedHomeIndex.value == 1`.

**Comment by Linxianyunqing** [comment]
I'll give it a try


---Original---
From: ***@***.***&gt;
Date: Thu, Dec 12, 2024 10:42 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [derec30240/TinyNote] Added task fuction (PR #3)




  
You shouldn't create a new floatingActionButton in task_page. Instead, you should add the function to that one in the home_page. Because I'm not available for a few days, you can try it on yourself.
  
For example, yoy can modify the floatingActionPage.onPressed() in home_page in this way:
 floatingActionButton: FloatingActionButton(   onPressed: () {     (globalController.selectedHomeIndex.value == 0)       ? Get.to(() =&gt; NoteEditPage(type: 'add', title: '', content: ''))       : Get.to(() =&gt; TaskEditPage());   },
 
Then delete the floatingActionButton in the task_page, because it's just the body of theHomePage when globalController.selectedHomeIndex.value == 1.

**Comment by Linxianyunqing** [comment]
Despite doing so，the process still have problems. It can not back to the upper page .

**Comment by derec30240** [comment]
I have fixed those bugs and committed to the `task_function` branch in my repository. Thanks for your contribution.

**Pull request closed without merging**
